name: transcripts_env
dependencies:
  - pip==25.1.*
  - python==3.11.*
  - pip:
    - transformers==4.52.3
    - torch==2.7.0
    - huggingface-hub==0.31.4
    - accelerate==1.7.0
    - hf_xet==1.1.2
    - pandas==2.2.3
    - pytest==8.3.5
    - scikit-learn==1.6.1
    - matplotlib==3.10.3
